export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const ADD_TO_CART = 'ADD_TO_CART';

export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';

export const DECRESASE_QUANTITY = 'DECRESASE_QUANTITY';

export const DELETE_FROM_CART = 'DELETE_FROM_CART'

export const RESET_STORE = 'RESET_STORE';